### ISSUE TITLE
🐛 Bug | Issues with add a link shortcut (ctrl+k)

### ISSUE THREAD

**Issue by whoabuddy** [sigle/sigle#116]
## Description

When using ctrl+k to add links, I noticed two small issues that affect usability. 

1. The modal auto focuses on the link name instead of the link address, so when trying to use ctrl+k then ctrl+v to paste, it lands in the wrong spot. Ideally I would be able to chain ctrl+k, ctrl+v, and enter.

1. After closing the modal to save the link, it jumps to the top of the page. Since I write really long blog posts this means scrolling back down and trying to find my place again. :nerd_face: 

**Screenshots**

None.

## Device

- OS: Linux Mint
- Browser: Vivaldi
- Version: not in front of it atm but can check if needed. 

Let me know if you need any additional info!

**Comment by pradel** [comment]
@whoabuddy I was able to reproduce the point 2, I will try to fix this behavior it can be pretty annoying :D 

For point 1 indeed that would be a nice improvement, thanks for reporting :)

**Comment by whoabuddy** [comment]
@pradel Happy to help, sometimes it's the little things! :microscope:

**Comment by pradel** [comment]
Fixed in the new editor
