### ISSUE TITLE
💡 RFC | Save post content as markdown in Gaia

### ISSUE THREAD

**Issue by pradel** [sigle/sigle#131]
## Description

The goal of this RFC is to find a good format to store the blog post contents in the user Gaia storage. Sigle is currently using [slatejs](https://github.com/ianstormtaylor/slate) for it's editor. We use the version `0.47.X` and would like to upgrade to the latest slate version. The problem is that slate released a major breaking change in the `0.50.X` version regarding how the data is formatted. In a centralised way, it should be fairly easy to migrate the current data to this new format using a database migration.

In a decentralized world, this is quite different as Sigle can't write to the user storage on his behalf. As there is no automatic way to do the migration we will need to keep a migration script in our codebase for a very long time (1+ year or maybe forever).

This issue brings actually a bigger problem, what format is the best to store the blog post content. We need to find a solution so this situation does not happen again in the future.

The solution will need to cover the following requirements:

- No lock-in - Is not tied to an editor (current format is tied to slate < 0.47)
- Extensible - we should be able to create custom blocks of content (eg: image carousel)
- Safe - we need to protect the user from XSS attacks etc.. (allow only some kind of blocks)
- Standard - another app could use the same format to render the content

**The user will not see any change in how the editor is currently working**, these changes will be done in the background, we do not plan (for now) to have a brand new editor (eg: markdown with side preview). 

## Markdown

https://daringfireball.net/projects/markdown/syntax

### Format

For the following article:

![Screenshot 2020-10-17 at 18 09 03](https://user-images.githubusercontent.com/5749437/96347721-e30e2200-10a3-11eb-9e87-188ccddd992d.png)

Slate format:

```json
{
  "object": "value",
  "document": {
    "object": "document",
    "data": {},
    "nodes": [
      {
        "object": "block",
        "type": "paragraph",
        "data": {},
        "nodes": [
          { "object": "text", "text": "Simple lorem ipsum ", "marks": [] },
          {
            "object": "inline",
            "type": "link",
            "data": { "href": "https://app.sigle.io/" },
            "nodes": [{ "object": "text", "text": "with a link", "marks": [] }]
          },
          { "object": "text", "text": ", voila.", "marks": [] }
        ]
      }
    ]
  }
}
```

Markdown format:

```md
Simple lorem ipsum [with a link](https://app.sigle.io/), voila.
```

### Requirements

- No lock-in: It is not tied to any editor and can be rendered easily in any programming language
- Extensible: We can create custom block contents but at the same time the format limits the blocks we can create. Eg we can't really create 2 columns of text side by side except if we are mixing markdown and HTML tags.
- Safe: Markdown is safe as we can only render the markdown tags and avoid rendering the HTML tags.
- Standard: There are multiple flavours of markdown but the GitHub standard is widely adopted already.

### Libraries

Here is a list of libraries that can be used to parse the markdown content. More research is needed to pick the good one.

- [markdown-it/markdown-it](https://github.com/markdown-it/markdown-it)
- [markedjs/marked](https://github.com/markedjs/marked)
- [jonschlinkert/remarkable](https://github.com/jonschlinkert/remarkable)
- [commonmark/commonmark.jst](https://github.com/commonmark/commonmark.js)
- [showdownjs/showdown](https://github.com/showdownjs/showdown)

### Conclusion

The markdown format looks like the most simple solution, it can be integrated super easily, is fast to parse and render. The only downside could be the lack of customisation if we want to create custom blocks. This can be solved using HTML blocks but at the same time will complicate the implementation.

Any feedback is welcome regarding this change :) I would love to add more options to this list!

**Comment by whoabuddy** [comment]
I think this is a great idea! Markdown is very easy to read, a widely adopted standard, and would make the back-end data more portable. Looking at the comparison of the two, markdown is much simpler while achieving the same goals for format and rendering.

For one of my projects I am currently using [Hugo](https://gohugo.io) and [Forestry](https://forestry.io), which stores data in markdown format inside of a git repo. I believe [they use commonmark](https://forestry.io/docs/editing/markdown-editor/) and some (if not all) of the [code is open source](https://github.com/forestryio/).

I see markdown meeting all of the requirements listed as long as the inclusion of raw HTML is blocked (as mentioned), and the extensibility can come from implementations in the app, e.g. options to insert a table, toc, or similar. Tagging #87 and #100 as related issues/ideas.

To the comment on the editor / front-end experience, one of my challenges as a writer is that I've become so used to using markdown that I end up writing out my posts, thoughts, and ideas in that format - then have to format it again to post on Sigle. It can get a bit tedious. I tend to use the preview function in my text editor then copy and paste small portions at a time, followed by formatting the titles, links, etc, using the slate.js editor.

**Comment by pradel** [comment]
> I see markdown meeting all of the requirements listed as long as the inclusion of raw HTML is blocked (as mentioned), and the extensibility can come from implementations in the app, e.g. options to insert a table, toc, or similar. Tagging #87 and #100 as related issues/ideas.

@whoabuddy To explain a bit more my concern with this, if we take for example a simple link it can be done that way:

```
[link](url)
```

But now let say I want to let the user choose if the link should open in a new tab (using target _blank). I could use some kind of plugins to add data attributes to the markdown, but then I am breaking the standard.

```
[link](url){:target="_blank"}
```

Another option is to convert it to html

```
<a href="http://example.com/" target="_blank">Hello, world!</a>
```

To make it more secure, I could only allow some tags in the link HTML element and accept only text inside the tag. But this looks like a workaround to fix a simple problem. I like the plugin approach as it can be applied to any tag and you don't switch to HTML. But at the same time if you just copy paste the markdown content from your Gaia storage to another markdown editor, the plugin format will not work.

> To the comment on the editor / front-end experience, one of my challenges as a writer is that I've become so used to using markdown that I end up writing out my posts, thoughts, and ideas in that format - then have to format it again to post on Sigle. It can get a bit tedious. I tend to use the preview function in my text editor then copy and paste small portions at a time, followed by formatting the titles, links, etc, using the slate.js editor.

This would definitely be improved by this proposal. Just copy-pasting some markdown content would be easily converted by the editor.

**Comment by pradel** [comment]
For example this package looks really cool https://github.com/arve0/markdown-it-attrs and would allow us to solve a lot this customisation problem that markdown is bringing.

**Comment by dantrevino** [comment]
I faced this as well, with NoteRiot.  Originally I was encoding some framework-specific colors into notes, and have left migration code in place for a long while now.

Regarding actual content, NoteRiot saves content as markdown currently (using tui/markdown-it), but we're actually trying to go the other direction because of Markdown's limitations. I'm currently playing with saving content in HTML (sanitized) in current daily builds.

**Comment by dantrevino** [comment]
I should add if you find out any information that would affect document collections, please add it in the forum: https://forum.blockstack.org/t/proposal-create-a-document-collection-for-cross-app-data-sharing/9286

**Comment by pradel** [comment]
@dantrevino looks like I am not the only one, good to know :D 

Did you create some kind of UI migration to migrate all the content of the logged-in user, or do you apply the new format only to the new / updated objects?

**Comment by dantrevino** [comment]
@pradel I'm not getting the user involved at all... I just convert during load from gaia, if required.

**Comment by pradel** [comment]
Adding a file listing markdown specs I was not aware of before.

[markdown_comparison.pdf](https://github.com/pradel/sigle/files/7735772/markdown_comparison.pdf)
