### ISSUE TITLE
🐛 Bug | Login with Stacks Wallet breaks blogging links (tested on Brave)

### ISSUE THREAD

**Issue by vthukral94** [sigle/sigle#207]
## Description

Blockstack login is deprecated & is being replaced by Stacks wallet. I created a Sigil account with Stacks Wallet & published a blog. Unfortunately the published blog doesn't get a valid URL. In my case it was `https://sf2mxje3xoh4kelebysim/`. The blog dashboard link doesn't seems to be valid as well.

## Screenshots

- [Screenshot 1](https://ibb.co/jLB7Kjn)
- [Screenshot 2](https://ibb.co/dpgR6Bb)
- [Screenshot 3](https://ibb.co/RDBDHLn)

## Device

- OS: macOS Big Sur 11.4
- Browser: Brave 
- Version: 1.26

**Comment by pradel** [comment]
We are working on a fix for this one!
