### ISSUE TITLE
Redesign profile page

### ISSUE THREAD

**Issue by pradel** [sigle/sigle#272]
## Description

> Waiting for updated Q1 designs

![Capture d’écran 2022-01-03 à 17 12 52](https://user-images.githubusercontent.com/5749437/147953516-7545b389-620b-4096-83ba-8e41ee2b3f3a.png)

**Comment by QuentinSaubadu** [comment]
The updated version of the Profile page is here.

The dashboard is your profile page when connected.
The profile page is someone else profile page.
You can see your own profile page as the others see it if you log out.

MY DASHBOARD:
<img width="1032" alt="Capture d’écran 2022-04-11 à 10 54 41" src="https://user-images.githubusercontent.com/7244762/162701200-d4f373d8-0985-4466-963f-97922374f82e.png">

- Cover image removed
- Story cards updated

PROFILE PAGE:
<img width="1033" alt="Capture d’écran 2022-04-11 à 10 56 06" src="https://user-images.githubusercontent.com/7244762/162701484-be55fe47-6437-44b5-8d65-e2065dae1b15.png">

- Side Menu removed
- New UI story cards
**- The Subscribe CTA will have to be displayed when the subscribing mechanism will be done.**

**Comment by pradel** [comment]
@QuentinSaubadu can this one be closed?
