### ISSUE TITLE
⚡ Feature | Editor keyboard shortcuts

### ISSUE THREAD

**Issue by pradel** [sigle/sigle#276]
## Description

On the bottom right corner of the editor page the user can click on the keyboard and a list of available shortcuts should be visible.

![Capture d’écran 2022-01-17 à 09 55 29](https://user-images.githubusercontent.com/5749437/149738312-b341aee6-31b4-472a-9b1d-10331d90cbd6.png)

> @pradel to create the list of available shortcut for the new Editor

The current editor shortcuts are listed here https://docs.sigle.io/editing/keyboard-shortcuts

**Comment by pradel** [comment]
Good start https://tiptap.dev/api/keyboard-shortcuts

**Comment by QuentinSaubadu** [comment]
@gregogun New shortcut keyboards below.

Here is the list of shortcuts to add:

### Essentials
Copy / Control C / Cmd C
Cut / Control X / Cmd X
Paste / Control V / Cmd V
Paste without formatting / Control Shift V / Cmd Shift V
Undo / Control Z / Cmd Z
Redo / Control Shift Z / Cmd Shift Z
Add a line break / Shift Enter / Shift Enter

### Text Formatting
Bold / Control B / Cmd B
Italicize / Control I / Cmd I
Underline / Control U / Cmd U
Strikethrough / Control Shift X / Cmd Shift X
Code / Control E / Cmd E

### Paragraph Formatting
Apply normal text style / Control Alt 0 / Cmd Alt 0
Apply heading style 2	Control Alt 2	Cmd Alt 2
Apply heading style 3	Control Alt 3	Cmd Alt 3
Ordered list / Control Shift 7 / Cmd Shift 7
Bullet list	Control Shift 8	Cmd Shift 8
Blockquote / Control Shift B / Cmd Shift B
Code block / Control Alt C / Cmd Alt C

### Text Selection
Select all /Control A / Cmd A
Extend selection one character to left / Shift ← / Shift ←
Extend selection one character to right / Shift → / Shift →
Extend selection one line up / Shift ↑ / Shift ↑
Extend selection one line down / Shift ↓ / Shift ↓
Extend selection to the beginning of the document / Control Shift ↑ / Cmd Shift ↑
Extend selection to the end of the document / Control Shift ↓ / Cmd Shift ↓

<img width="1061" alt="Capture d’écran 2022-02-28 à 16 25 24" src="https://user-images.githubusercontent.com/7244762/156012886-36f01edf-3815-410f-9c11-a009ca8dfa27.png">
