### ISSUE TITLE
Redesign Toast component

### ISSUE THREAD

**Issue by pradel** [sigle/sigle#285]
## Description

Redesign Toast component.

> @QuentinSaubadu TODO designs with all the possible status (error, info etc..).

Notes:

- 23/01/2022 - Just saw that the toast component is shown as "coming soon" in the radix docs, might be better for us to wait for the release of the component before starting this task.
- 1/04/2022 - Radix released the component in beta, should unblock this task https://www.radix-ui.com/docs/primitives/components/toast

**Comment by QuentinSaubadu** [comment]
> ## Description
> Redesign Toast component.
> 
> > @QuentinSaubadu TODO designs with all the possible status (error, info etc..).
> 
> Technical question:
> 
> * Are we changing the lib we use for the toasts or do we keep this one?

Can I get somewhere a list of all different possible status?

**Comment by pradel** [comment]
So far in the app we are just using toast for success and error messages

**Comment by pradel** [comment]
@QuentinSaubadu radix released their toast component so you can create the specs for this one https://www.radix-ui.com/docs/primitives/components/toast
