### ISSUE TITLE
🐛 Bug | Issues with code blocks in dark mode

### ISSUE THREAD

**Issue by pradel** [sigle/sigle#405]
## Description

When you enable dark mode in the app, the code blocks are not working properly.

We need to fix the style of:
- inline code blocks
- multi-line code blocks

![Screenshot 2022-03-22 at 15 26 33](https://user-images.githubusercontent.com/5749437/159504956-32c2d44c-f223-495f-a756-d8a0b7d12ca9.png)

**Comment by QuentinSaubadu** [comment]
@gregogun can we make it the same for light and dark mode and change the background for both of them to color n°2(dark mode) with a line stroke (color 7 but respecting the light and dark themes)
<img width="479" alt="Capture d’écran 2022-03-23 à 12 50 07" src="https://user-images.githubusercontent.com/7244762/159692936-ccbeb427-ea1a-4e26-9e77-caa061cdebc4.png">

It will look like this:
<img width="975" alt="Capture d’écran 2022-03-23 à 12 52 45" src="https://user-images.githubusercontent.com/7244762/159693407-f7f3ddb6-a189-47d7-82df-568795eb3cf1.png">

@pradel you got with it?

**Comment by pradel** [comment]
Sounds good 👌
