### ISSUE TITLE
⚡ Feature | Dashboard zero data view

### ISSUE THREAD

**Issue by pradel** [sigle/sigle#408]
## Description

With the release of the new dashboard, we need to create the zero data view. When a user first creates an account he will see when the list of blog posts is empty.

Current one:
<img width="1508" alt="Screenshot 2022-04-01 at 14 24 13" src="https://user-images.githubusercontent.com/5749437/161262637-5cdfdd86-c430-4aa7-88c1-3eb0e1e5a69b.png">

**Comment by QuentinSaubadu** [comment]
Redesign done:

<img width="1064" alt="Capture d’écran 2022-04-11 à 10 41 10" src="https://user-images.githubusercontent.com/7244762/162698648-2fdb1cc6-bde9-4664-9c82-717bbd4f1775.png">

- The illustration is a Gif (250px width):
![no-draft](https://user-images.githubusercontent.com/7244762/162698898-57a5fdb0-5a0f-4fd9-9974-4d61a56c7307.gif)

- Write a Story CTA should bring you to the Editor

- Cards placeholders are designed and can be found here: https://www.figma.com/file/uPVMeBq0bERyViiRMXzLN8/?node-id=1038%3A1646

- Let's place 2 placeholders only
