### ISSUE TITLE
⚡ Feature | Change meta text when sharing a story

### ISSUE THREAD

**Issue by QuentinSaubadu** [sigle/sigle#418]
## Description

Once a user can add his Twitter handle in his settings, 
we should change the text when sharing a story on Twitter for:

Read "title" by "@twitterhandle"

<img width="715" alt="Capture d’écran 2022-04-07 à 09 56 07" src="https://user-images.githubusercontent.com/7244762/162149365-f98ddb79-49fc-49d5-bbd7-2cfb092f0096.png">

**Comment by pradel** [comment]
Already done
