### ISSUE TITLE
⚡ Feature | Set metadata for your profile page

### ISSUE THREAD

**Issue by QuentinSaubadu** [sigle/sigle#477]
Users need to be able to share their Sigle page on socials using the good metadata like this:
<img width="654" alt="Capture d’écran 2022-05-17 à 16 12 10" src="https://user-images.githubusercontent.com/7244762/168850986-9f1d457b-4843-4735-a32d-908c12618541.png">

Instead of this:
<img width="623" alt="Capture d’écran 2022-05-17 à 17 36 00" src="https://user-images.githubusercontent.com/7244762/168851176-186a98c8-dbbf-49ba-8cd8-342c1834ee78.png">

To do so:
- Take the user name (if the user didn't set a custom name, then take the ID) followed by "- Sigle". Ex: quentin.btc - Sigle")
- Take the user description in the settings, if the user didn't set a custom domain, use the default text we are using when sharing app.sigle.io on socials: Sigle is a decentralised open-source platform empowering Web3 creators......
- Take the user profile picture, if the user didn't upload a PFP, then leave this part blank. We can think about generating an image in the future as below:
<img width="399" alt="Capture d’écran 2022-05-17 à 17 45 09" src="https://user-images.githubusercontent.com/7244762/168853267-9261ca02-ea2a-4c3e-bb13-2a4fdc9a1459.png">

Final result should be like this:
<img width="920" alt="Capture d’écran 2022-05-17 à 17 47 42" src="https://user-images.githubusercontent.com/7244762/168853874-bb87fcfc-6300-46d1-a05a-60081505341e.png">

Link to Figma card: https://www.figma.com/file/uPVMeBq0bERyViiRMXzLN8/Sigle-design-system?node-id=2220%3A2900

**Comment by pradel** [comment]
> Take the user description in the settings, if the user didn't set a custom domain, use the default text we are using when sharing app.sigle.io on socials: Sigle is a decentralised open-source platform empowering Web3 creators......

@QuentinSaubadu would it be better to have some kind of CTA (when the user did not setup any description), eg: "Read quentinsaubadu.btc stories on Sigle, decentralised open-source...."

**Comment by QuentinSaubadu** [comment]
> > Take the user description in the settings, if the user didn't set a custom domain, use the default text we are using when sharing app.sigle.io on socials: Sigle is a decentralised open-source platform empowering Web3 creators......
> 
> @QuentinSaubadu would it be better to have some kind of CTA (when the user did not setup any description), eg: "Read quentinsaubadu.btc stories on Sigle, decentralised open-source...."

"Read stories from "name" on Sigle, decentralised and open-source platform for Web3 writers" @pradel
