### ISSUE TITLE
🐛 Bug | Username registration fails and blocking the access to app

### ISSUE THREAD

**Issue by spnraju** [sigle/sigle#483]
## Description

I am logging in to the account after a long break and now I am prompted to create a username on the page "https://app.sigle.io/register-username" which is fine. But when I try to create one, it fails with `Failed to validate your registration request. Requested subdomain operation is invalid.`

On checking the browser console logs, I noticed the below.

- The username I am using is available. https://registrar.stacks.co/v1/names/ responds saying `{"status":"available"}` with status code as 404
- The POST call to register it using `https://registrar.stacks.co/register` fails with the status code as 409. The request payload has `owner_address` as Undefined.
- `user.profile.stxAddress` does have a valid value in the logs. But it does not have any key like `mainnet`.

From https://github.com/sigle/sigle/pull/480/files#diff-db502247e3b55308dc5e2f43412ae715799ac063eb46a9f47498c06bdc61f30bR221, I assume this is required for the registration. 

Please let me know if you would like to get more information from the console logs.

## Device

- OS: Windows 10
- Browser: Chrome 
- Version: 101.0.4951.67

**Comment by pradel** [comment]
@spnraju we just released the Hiro wallet login, could you please retry by creating a Hiro wallet account ? (or using an existing one ofc)

**Comment by spnraju** [comment]
@pradel It worked! But I remember having published a blog before. That is not accessible anymore. This was also created with the same hiro wallet id.
