### ISSUE TITLE
⚡ Feature | Share buttons on the public story page

### ISSUE THREAD

**Issue by pradel** [sigle/sigle#54]
We want visitors to be able to share articles to social media by simply clicking on a button (eg: twitter logo)

### Related

- Canny: https://sigle.canny.io/feature-requests/p/share-widget

**Comment by pradel** [comment]
@QuentinSaubadu some questions:
1. how should this behave on mobile?
2. is there the same thing at the bottom?

**Comment by QuentinSaubadu** [comment]
> @QuentinSaubadu some questions:
> 
> 1. how should this behave on mobile?
> 2. is there the same thing at the bottom?

Design will be updated as soon as the mobile version is made
