### ISSUE TITLE
⚡ Feature | HEADER - Redesign dropdown menu

### ISSUE THREAD

**Issue by QuentinSaubadu** [sigle/sigle#584]
It's time now to upgrade the dropdown menu.
FIGMA FILE: https://www.figma.com/file/uPVMeBq0bERyViiRMXzLN8/Sigle-design-system?node-id=2355%3A3457

Before: 
<img width="425" alt="Capture d’écran 2022-07-04 à 19 07 16" src="https://user-images.githubusercontent.com/7244762/177196509-40a4170a-f231-41bd-875c-9a1dcfe2319d.png">

After:
<img width="450" alt="Capture d’écran 2022-07-04 à 19 06 09" src="https://user-images.githubusercontent.com/7244762/177196516-1502406f-1095-483a-a2b3-6137bd7e9067.png">

Add the username on top followed by the ID extension and the profile picture.
Clicking on it brings you to the Profile page.

FIRST SECTION :  
The default font color is now 11.
Hover and on click mode didn't change.
Add icons on the left side.

SECOND SECTION:
The default font color is now 9.
Change "Switch theme" by "Dark mode" and add a toggle on the right side: https://www.figma.com/file/uPVMeBq0bERyViiRMXzLN8/Sigle-design-system?node-id=3095%3A5547

THIRD SECTION:
Swap the red color on the logout tab for a grey 9

**Comment by pradel** [comment]
@QuentinSaubadu so we drop the "write" part in this menu? Can we keep it somehow?

**Comment by QuentinSaubadu** [comment]
@pradel Writing a new post is actually pretty rare, the only moment you do not see the button is when you're reading someone else's post (so not in a position to write). You basically know before opening the app that you wanna write something today, this is most of the time something you prepare, so I don't think at the end it makes really sense to have it constantly in the dropdown menu.
