### ISSUE TITLE
⚡ Feature | EXPLORE - Add login modal on follow button 

### ISSUE THREAD

**Issue by QuentinSaubadu** [sigle/sigle#629]
On the Explore page, when logged out, we need to display the "follow" button to convert the users.
When the logged-out user clicks on the "follow" button, display the modal below:
<img width="675" alt="Capture d’écran 2022-07-26 à 09 50 04" src="https://user-images.githubusercontent.com/7244762/180952885-48645058-0034-48c3-b6b4-285a9ec98d6f.png">

https://www.figma.com/file/elxKahbV8rj85IWOEyZeVu/Product-design?node-id=4187%3A29767

**Comment by pradel** [comment]
@QuentinSaubadu can we do a generic modal that can be used for any part where the user is required? Meaning remove the "to follow writers" etc.. have some generic text

**Comment by QuentinSaubadu** [comment]
> @QuentinSaubadu can we do a generic modal that can be used for any part where the user is required? Meaning remove the "to follow writers" etc.. have some generic text

100%! That's a good idea.

We could replace the text by:

> 
> Login to continue
> To proceed, you must first be logged in.
> 
> Button> Cancel Button>Go to login page

If you're ok with that, I'll make it on Figma and edit this issue @pradel

**Comment by pradel** [comment]
@QuentinSaubadu I think the content of the modal should show the benefits of joining Sigle, eg: list the features you will get by creating a accounts / logging-in. Wdyt?

**Comment by gregogun** [comment]
@QuentinSaubadu @pradel as we are adding the login prompt on the user cards which are used for the explore and profile page, I'm wondering if it also makes sense to add the same logic for other areas in the app where we currently hide the follow button (we also hide it in the profile card on public story)—wdyt?

**Comment by QuentinSaubadu** [comment]
> @QuentinSaubadu @pradel as we are adding the login prompt on the user cards which are used for the explore and profile page, I'm wondering if it also makes sense to add the same logic for other areas in the app where we currently hide the follow button (we also hide it in the profile card on public story)—wdyt?

@gregogun that's a good idea, let's do that.

@pradel I thought we already discussed it and find out that wasn't a priority, and that we could improve the modal later on, but I can try to make something quick. @gregogun I might change a little bit if I manage to put the list of features.

**Comment by QuentinSaubadu** [comment]
<img width="908" alt="Capture d’écran 2022-10-21 à 14 54 17" src="https://user-images.githubusercontent.com/7244762/197201692-b6ed5129-8a05-4da4-a8dc-c076db7f42ae.png">

Final version on FIGMA: https://www.figma.com/file/uPVMeBq0bERyViiRMXzLN8/Sigle-design-system?node-id=3138%3A7449

@gregogun @pradel
