### ISSUE TITLE
⚡ Feature | EDITOR 📱 - New paragraph layout

### ISSUE THREAD

**Issue by QuentinSaubadu** [sigle/sigle#637]
Rearrange the fonts and spacings of the content frame on the mobile editor.
Check all the fonts and spacings on the 3 pages below:
https://www.figma.com/file/elxKahbV8rj85IWOEyZeVu/Product-design?node-id=4229%3A30439
<img width="1060" alt="Capture d’écran 2022-07-29 à 16 37 42" src="https://user-images.githubusercontent.com/7244762/181783687-ba51f949-77e9-4d4c-a20f-a68d05a32dd1.png">

**Comment by pradel** [comment]
Closed by #641
