### ISSUE TITLE
⚡ Feature | Drag and drop images in text container

### ISSUE THREAD

**Issue by QuentinSaubadu** [sigle/sigle#652]
Users need to be able to drag and drop images (jpg/png/gif..) from their desktop to the editor.

When dragging an image to the editor, we'll display a thin grey (7) line of 2px between the paragraphs so the user can clearly see where he's placing the image: 
<img width="1015" alt="Capture d’écran 2022-08-22 à 17 17 32" src="https://user-images.githubusercontent.com/7244762/185958890-8b3e676f-5d42-44f6-9b18-5b9e8573ff77.png">

releasing the left mouse click will drop the image in the wanted paragraph and will load like shown
Use the spinner icon (white) we are using on the login page
Use a color 12 overlay 70% opacity to cover the image while loading: 
<img width="1009" alt="Capture d’écran 2022-08-22 à 17 17 38" src="https://user-images.githubusercontent.com/7244762/185959137-fcba87c5-9e69-4ba8-bd08-32a422408b49.png">

FIGMA FILE: https://www.figma.com/file/elxKahbV8rj85IWOEyZeVu/Product-design?node-id=4648%3A35347

**Comment by pradel** [comment]
@gregogun to handle the dropzone part, we already have the react-dropzone npm package so please use this one :)
