### ISSUE TITLE
⚡ Feature | Add CTA on mobile 

### ISSUE THREAD

**Issue by QuentinSaubadu** [sigle/sigle#653]
While waiting for the hamburger menu to be deployed later, we need to be able to write a new story at any time on the mobile version.

To do that, place a mobile CTA (**Use this Figma file for the CTA:** https://www.figma.com/file/uPVMeBq0bERyViiRMXzLN8/Sigle-design-system?node-id=2635%3A5002) On the top right corner of the followed pages:
- Drafts
- Published
- Analytics
- Profile (The page is not working on mobile version tho)
<img width="618" alt="Capture d’écran 2022-08-24 à 12 30 30" src="https://user-images.githubusercontent.com/7244762/186396665-68137d08-151f-4d35-9cdd-61cdee536553.png">

FIGMA FILE : https://www.figma.com/file/elxKahbV8rj85IWOEyZeVu/Product-design?node-id=4662%3A31674

**Comment by pradel** [comment]
@QuentinSaubadu isn't it better to just fix the hamburger menu? This seems like work that will be removed soon no ?
