### ISSUE TITLE
⚡ Feature | Update editor placeholder on mobile

### ISSUE THREAD

**Issue by gregogun** [sigle/sigle#671]
## Description

Currently, even though we don't have the slash commands active on mobile, the placeholder for paragraph node still shows `Type '/' for commands` so needs to updated.

**Comment by gregogun** [comment]
@QuentinSaubadu @pradel for this one do you guys think it's best to have some placeholder (e.g. 'Type something') or we just leave it blank?

**Comment by QuentinSaubadu** [comment]
> @QuentinSaubadu @pradel for this one do you guys think it's best to have some placeholder (e.g. 'Type something') or we just leave it blank?

Good point, I think "Type something..." is good! Let's go with that
