### ISSUE TITLE
🐛 Bug | Follow counter not working on small profile cards

### ISSUE THREAD

**Issue by QuentinSaubadu** [sigle/sigle#682]
The counter on the small profile cards (when hovering a writer's name on an article) is not updating when we click on the "follow" CTA.

See screen recording here:

https://user-images.githubusercontent.com/7244762/191268470-0f2430ce-9813-4492-a1f0-a4e0cfb9f408.mov

**Comment by pradel** [comment]
@gregogun could be the params missing maybe?
