### ISSUE TITLE
🐛 Bug | Couldn't run the server in localhost

### ISSUE THREAD

**Issue by sanjayk0508** [sigle/sigle#736]
I tried running the site in my local IDE by following the contribution guide steps.
I ran `pnpm install` & this is the error that came up:

```
 pnpm install
pnpm : The term 'pnpm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path 
was included, verify that the path is correct and try again.
At line:1 char:1
+ pnpm install
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (pnpm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I even tried some other methods to run the server but it seems like nothing worked out.

**Comment by gregogun** [comment]
Hi @sanjayk0508, 

Which OS and terminal are you using when you face this issue?

**Comment by sanjayk0508** [comment]
Hey Greg,

Windows 10 Pro
OS build: 19044.2130
System type: 64-bit operating system, x64-based processor

For Terminal I'm using vscode

**Comment by pradel** [comment]
Hey @sanjayk0508, from this error it seems that pnpm 7+ might not installed on your system.
Installation guide: https://pnpm.io/installation
Contributing guide: https://github.com/sigle/sigle/blob/main/CONTRIBUTING.md

**Comment by pradel** [comment]
Closing the issue, please let us know if you are still facing the issue
