### ISSUE TITLE
⚡ Feature | Markdown shorcuts

### ISSUE THREAD

**Issue by pradel** [sigle/sigle#87]
## Description

Implement markdown shorcuts for the editor:
- allow copy paste of a markdown post to be formatted directly
- create a documentation page showing all the possible shortcuts

Example: https://www.slatejs.org/examples/markdown-shortcuts

**Comment by whoabuddy** [comment]
I think this would be a great addition, however when I tested it out via the slatejs.org example, it appears copying/pasting the Markdown code from my text editor ends up all in one big unformatted paragraph. 

When typing it in line-for-line into the app, it works, but this is not my typical use case for a blog for me. I keep my drafts in a text editor and copy/paste/post when ready to publish. That way I have them all on my device and no need for an Internet connection.

I do like the inline editor the way it is styled now, though, and I could see the slatejs option being an awesome alternative for someone using that same UI. I would prefer a Github/Discourse-styled write/preview tab, but that's probably just me! :smile: 

_Side request: I'd also like a way to designate code blocks and make nested lists in the current UI!_

_2nd side request: while creating/formatting my post I hit ctrl+k and went to paste+enter my link out of habit... and it took me to a new page in my browser where I lost everything I typed in and manually formatted. It's just a blank draft. Ouch!_

Attached is the Markdown code from my "first post" as part of my blog (in TXT format) for [whoabuddy.id.blockstack](https://app.sigle.io/whoabuddy.id.blockstack). This time around I ended up copying it in from the Markdown preview in Atom - it brought over the text without formatting and was a mess to touch up. I could see this being tedious in the long run especially when the formatting gets lost.

[20200218 Blog - A Day in My Life.txt](https://github.com/pradel/sigle/files/4220414/20200218.Blog.-.A.Day.in.My.Life.txt)

Also, for the documentation, could you use [an existing cheat sheet like this one?](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) No need to reinvent the wheel!

**Comment by pradel** [comment]
Should be solved by #252

**Comment by pradel** [comment]
Fixed in the new editor
